version: '3'

services:
  blockchain:
    build: ./app/smart-contract
    container_name: blockchain
    image: blockchain
    ports:
      - 8545:8545
      - 9545:9545
    volumes:
      - ./app/smart-contract:/app/smart-contract
    command: >
      sh -c "
      truffle develop &&
      truffle migrate &&
      
      tail -f /dev/null
      "
    restart: always

