version: '3'

services:
  blockchain:
    build: ./smart-contract
    container_name: hardhat
    image: hardhat
    command: >
      sh -c "
        npx hardhat node
      "
    ports:
      - 8545:8545
      - 22000:22000
    volumes:
      - ./smart-contract:/app
      - /app/node_modules
  
  webapp:
    build: ./app/webapp
    container_name: webapp
    image: webapp
    command: > 
      sh -c "
        npm start
      "
    ports:
      - 3000:3000
    volumes:
      - ./app/webapp:/app
      - /app/node_modules